/// Flutter icons HomeIconsSoloTec
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIconsSoloTec
///      fonts:
///       - asset: fonts/HomeIconsSoloTec.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HomeIconsSoloTec {
  HomeIconsSoloTec._();

  static const _kFontFam = 'HomeIconsSoloTec';
  static const String? _kFontPkg = null;

  static const IconData bi_thermometer_half =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer1sensacao_icon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_moistureumidade_icon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
